// packages/vue-app/src/components/Signup.vue
<template>
<div class="container-center"> 
     <img src="https://vuejs.org/images/logo.png" alt="VueJS logo" width="100" />
    <h1>Signup </h1>

<router-link to="/">Signin</router-link>
</div>
</template>
<script>

export default {   
}
</script>
<style scoped>
.container-center{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
</style>

// packages/react-app/src/components/Signup.js
import React from 'react';
import { Link } from 'react-router-dom';
import './style.css'
export default function SignUp({ onSignIn }) {

  return (
    <div className="container-center"> 
    <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" width="100"/>
       SignUp
       <Link to='/signin'>Signin</Link>
       <Link to='/'>Home</Link>
   </div>
  );
}
